#!/usr/bin/python


import re
import os
import os.path
import sys
import getopt

from lib.util import *
from lib.pdfsizeopt.PdfObj import PdfObj
from lib.pdfsizeopt.PdfData import PdfData

# pdfsizeopt: PDF file size optimizer
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
# pdfsizeopt works with Python 2.4, 2.5, 2.6 and 2.7. It doesn't work with
# Python 3.x.
#
# This Python script implements some techniques for making PDF files smaller
# without any visual quality or interactivity loss.
# See also https://github.com/pts/pdfsizeopt for more information,
# including documentation, installation instructions, a white paper describing
# what optimizations are done in this script and why, and presentation slides
# about the same.
#
# This script needs a Unix system, with Ghostscript (gs), sam2p or imgdataopt,
# pngout (--use-pngout=no to disable), jbig2 (--use-jbig2=no to disable)
# Future versions may relax the system requirements.
#
# This script doesn't optimize the serialization of objects it doesn't modify.
# Use tool.pdf.Compress in Multivalent.jar from http://multivalent.sf.net/ for
# that. This script runs Multivalent if --use-multivalent=yes is specified.

__author__ = 'pts@fazekas.hu (Peter Szabo)'


FLAGS_HELP = r"""
--optimize; default mode
  Optimize a PDF: read it, make it smaller without quality loss, write the
  output PDF. This is the default mode of operation.
--version
  Print pdfsizeopt version info and exit.
--help
  Display help with all command-line flags.
--helpshort
  Display help without command-line flags.
--stats
  Display byte size statistics of various object types in a PDF.
--do-optimize-images=YES_NO; default: yes
  Do the image optimizations? If yes, this can be slow, because various
  internal compression algorithms and external image optimizer programs will
  be run on each image, and some of them are slow.
--use-pngout=YES_NO; default: yes
  Run pngout for optimizing images embedded in PDF? Please note that pngout
  is very slow. Needs the external optimizer tool pngout.
--use-jbig2=YES_NO; default: yes
  Run jbig2 for optimizing images embedded in PDF? Affects only images with
  2 colors. Needs the external optimizer tool jbig2.
--use-sam2p-pr=YES_NO; default: yes
  Run sam2p with predictors enabled for optimizing images embedded in PDF?
  Needs external optimizer tool sam2p.
--use-image-optimizer=PROG[,...]
  Run the specified image optimizer programs (comma-separated list) for
  optimizing images embedded in PDF. Can be specified multiple times. If
  specified, the default because --use-pngout=no and --use-jbig2=no. Only
  some well-known, built-in PROG values can be specified (e.g. sam2p,
  imgdataopt, pngout, jbig2, zopflipng, optipng, ECT, advpng). Specifying
  the same program multiple times would run it multiple times, so don't do
  it. The special values no or none indicate that no program should be run
  (but more values can be appended later).
--use-image-optimizer=CMD_PATTERN
  Run the specified image optimizer program command-line for optimizing
  images embedded in PDF. This is in addition to the other values for the
  same flag. CMD_PATTERN is an os.system command-line pattern, which must
  contain at least one space, and %(targetfnq)s, to which the target filename
  would be substituted. Additionally, it may contain %(sourcefnqs) for the
  source filename. Both of them will be autogenerated temporary filenames.
  (There are some other sobstitutions as well in CMD_PATTERN.) The CMD_PATTERN
  can be used to run an image optimizer whose command-line syntax is not
  built in to pdfsizeopt.
--do-fast-bilevel-images=YES_NO; default: no
  Disable some slow image optimizers for bilevel images in favor of jbig2.
  This flag is smart, and it disables optimizers only if jbig2 is enabled,
  and the to-be-disabled optimizer is very unlikely to be better than jbig2.
--do-require-image-optimizers=YES_NO; default: yes
  Check for the existence of image optimizer programs, before reading the
  input PDF?
--do-debug-image-optimizers=YES_NO; default: no
  Print a list of image optimizer CMD_PATTERN values to be used, before
  reading the input PDF? This is useful for debugging. It also reveals the
  CMD_PATTERN of the well-known, built-in PROG values.
--do-optimize-fonts=YES_NO; default: yes
  Do the font optimizations? Most font optimizations apply to Type1 and
  Type1C (CFF) fonts only. There are no Type42 (TrueType) font optimizations.
--do-unify-fonts=YES_NO; default: yes
  Unify (merge) fonts with similar names, thereby removing glyph shape
  duplication? It only works with Type1 and Type1C fonts which are named as
  subsets of the same font. Many other restrictions also apply. It is
  careful and paranoid: if unification doesn't work for some fonts, it keeps
  them intact.
--do-keep-font-optionals=YES_NO; default: no
  Keep optional information about fonts in the PDF? The optional information
  is not needed for rendering and interactivity, it was needed by the document
  authoring system. Currently it applies only to the /CharSet field.
--do-regenerate-all-fonts=YES_NO; default: yes
  Parse and serialize all fonts? Currently it applies only to Type1 an Type1C
  fonts. It makes the output consistent, and it also makes some fonts a bit
  smaller. Doing it is not much slower (and it's actually faster if some fonts
  need /LZWDecode). However, Ghostscript is used for both parsing and
  serialization, and it may breaks some fonts (but it seldom happens nowadays).
  So in case of font problems, specify
  --do-unify-fonts=no --do-regenerate-all-fonts=no.
--do-double-check-type1c-output=YES_NO; default: no
--do-double-check-missing-glyphs=YES_NO (same as above, legacy flag name)
  After Type1C font serialization, parse it again, and check that the glyphs
  and most other fields are still there? It is slow, but it can reveal some
  bugs in Ghostscript.
--do-optimize-streams=YES_NO; default: yes
  Recompress all non-image streams, keep the smallest value. To optimize image
  streams, please use --do-optimize-images=yes.
--do-optimize-objs=YES_NO; default: yes
  Optimize all objects in a PDF in a generic way? It removes unused objects,
  it deduplicates objects, it reserialize object headers etc. These
  optimizations don't depend on the object type.
--do-optimize-obj-heads=YES_NO; default: yes
  Reserialize object headers? Only relevant if --do-optimize-objs=no (otherwise
  it's enabled regardless of the flag). It removes unnecessary whitespace and
  comments.
--do-ignore-generation-numbers=YES_NO; default: yes
  Ignore generation numbers in object definitions and references? If yes,
  it treats all generation numbers as 0. If no, it aborts on nonzero generation
  numbers.
--do-remove-generational-objs=YES_NO; default: yes
  Remove or renumber generational objects, making all objects in the output PDF
  non-generational? Currently this is not implemented properly, it just turns
  on the same optimizations as --do-optimize-objs=yes, and these are not
  related to generational object renumbering.
--do-unify-pages=YES_NO; default: yes
  Unify duplicate /Type /Page objects? It makes the PDF with duplicate pages
  a bit smaller. Disabling it increases compatibility with some old PDF
  viewers.
--do-generate-xref-stream=YES_NO; default: yes
  Generate the output PDF file with an xref stream (rather than an xref)?
  It produces smaller output. It should only be turned off for debugging.
--do-generate-object-stream=YES_NO; default: yes
  Generate the output PDF file with non-stream objects packed to an
  object stream (objstm)?
  It produces smaller output. It should only be turned off for debugging.
--do-decompress-flate=YES_NO; default: no
  Decompress all /Filter /FlateEncode streams in the output PDF? Doing so
  can make the output PDf much larger, so it should be enabled only for
  debugging, like this:
  --do-decompress-flate=yes --do-compress-uncompressed-streams=no.
--do-decompress-most-streams=YES_NO; default: no
  Decompress most compressed streams in the output PDF? Doing so
  can make the output PDf much larger, so it should be enabled only for
  debugging, like this:
  --do-decompress-most-streams=yes --do-compress-uncompressed-streams=no.
  Actually not all streams are decompressed, but only those which
  eventually get used in the output PDF, except if they have filter
  /DCTDecode or /JPXDecode (because such decompression is not deterministic
  and fully accurate).
--do-compress-uncompressed-streams=YES_NO; default: yes
  Compress stream objects in the output which are uncompressed? This is
  applied after the decompressions by the --do-decompres-... flags.
--use-multivalent=YES_NO; default: no
  Use the tool.pdf.Compress tool in Multivalent.jar to optimize the PDF even
  further, after applying the optimizations built in to pdfsizeopt? Not
  enabled by default, because it needs a copy of Multivalent.jar, which is
  not available for download or buying anymore.
--do-escape-images-from-multivalent=YES_NO; default: yes
  Hide images from Multivalent.jar, making it skip all image optimizations?
  It's useful to enable it by default, because Multivalent has some image
  processing bugs (including some compression predictor handling), thus it
  would garble the image with a /Predictor.
--do-debug-gs=YES_NO; default: no
  Display debug info about where pdfsizeopt is trying to find Ghostscript,
  whether the found Ghostscripts work, and which one was chosen? All this
  before reading the first input PDF.
--v=VERBOSITY; default: 190
  Controls the verbosity of pdfsizeopt (and the tools invoked by it), i.e.
  how much pdfsizeopt writes to stderr. Please note that pdfsizeopt and
  never writes to stdout (and it also redirects the tool output from stdout
  to sterr).
  10: Fatal errors, unhandled exceptions.
  20: As above, plus errors.
  30: As above, plus warnings.
  40: As above, plus a constant number of info messages containing progress
      updates.
  50: As above, plus info messages proportional to the input file size.
  60: As above, plus tool output. (Example tools: Ghostscript, sam2p, imgdataopt,
      jbig2.)
  190: As above.
  200: As above, plus debug info.
  999: Everything.
--quiet
  Equivalent to --v=20 : print only errors, fatal errors, unhandled exceptions.
--tmp-dir=DIR
  Directory to save temporary files to. pdfsizeopt will delete these files unless
  an uncaught exception is raised. If not specified or empty,
  then the environment variable TMPDIR will be used (TEMP on Windows) if it
  exists. If that's also missing, empty or it doesn't exist, then the directory
  containing the output file is used. (If running pdfsizeopt within Docker, only
  the default works.)
"""

# TODO(pts): Add a shorthand for (and then allow override later in the command-line -- or also earlier?): --do-optimize-images=no --do-optimize-fonts=no --do-optimize-objs=no --do-optimize-streams=no --do-decompress-most-streams=yes --do-generate-xref-stream=no --do-generate-object-stream=no
# TODO(pts): Add cleanup flag to os.remove temporary files even on an exception.
# TODO(pts): re.compile anywhere (no re.match or re.search).

# We don't want to have a '$' + 'Id' in this file, because downloading the
# script from http://pdfsizeopt.googlecode.com/svn/trunk/pdfsizeopt.py
# won't expand that to a useful version number.

__pychecker__ = 'maxlines=999 maxlocals=99 unusednames=self,cls maxreturns=99 maxbranches=9999'

bytearray_tostring = bytearray.__str__

TMP_PREFIX = '///dev/null/psotmp..'  # Will be overridden in main.

# Log everything by default. Will be overridden in main.
VERBOSITY = 999

logger = Logger(VERBOSITY)


def verify_gs(gs_cmd, is_verbose):
  q = '\''
  if sys.platform.startswith('win'):
    q = ''
  if is_verbose:
    logger.log_info('verifying Ghostscript: %s' % gs_cmd)
  gs_cmd2 = gs_cmd + ' -dNODISPLAY -c %s/GSOK === quit%s' % (q, q)
  # It would also work without RedirectOutput, because Ghostscript writes
  # the interesting message to stdout.
  f = os.popen(RedirectOutput(gs_cmd2, mode=True), 'rb')
  data = f.read()
  if is_verbose:
    logger.log_info('output from Ghostscript: %r' % data)
  if f.close():
    if is_verbose:
      logger.log_info('Ghostscript failed')
    return False
  lines = data.rstrip('\n').split('\n')
  if not lines or lines[-1] != '/GSOK':
    if is_verbose:
      logger.log_info('missing /GSOK from Ghostscript')
    return False
  lines.pop()
  if not lines or ' Ghostscript ' not in lines[0]:
    if is_verbose:
      logger.log_info('missing Ghostscript version info')
    return False
  lines = [line for line in lines if not line.startswith('Copyright ') and
           'NO WARRANTY' not in line]
  data = '; '.join(lines)
  # Example: data == 'GPL Ghostscript 9.02 (2011-03-30)'.
  if is_verbose:
    logger.log_info('Ghostscript version info: %r' % (data,))
  return data


def find_exe_on_path(prog):
  """Return pathname to the executable prog, or None if not found."""
  exe_ext = ''
  if sys.platform.startswith('win') and '.' not in os.path.basename(prog):
    exe_ext = '.exe'
  return find_on_path(prog + exe_ext)


def get_gs_command(is_verbose=False, _cache=[]):
  """Return shell command-line prefix for running Ghostscript (gs)."""
  if _cache:
    return _cache[0]
  prefix = ''
  if sys.platform.startswith('win') and os.getcwd().startswith('\\\\'):
    # Ghostscript doesn't with on Windows 8.1 if current directory is a UNC
    # path. (It seems to work on wine-1.6.2.) See
    # https://github.com/pts/pdfsizeopt/issues/24 for details.
    #
    # Please note that os.getcwd() on wine-1.6.2 returns r'UNC\...\...\...',
    # so this doesn't match. But it would work if it was changed to
    # r'\\...\...\...' in future Wine versions.
    #
    # We work it around by doing a chdir to C:\ before running Ghostscript,
    # and converting relative paths to absolute paths in the Ghostscript
    # command-line (done in ShellQuoteFileName(..., is_gs=True)).
    prefix = 'c:&cd \\&'
  elif not sys.platform.startswith('win'):
    # Make Ghostscript use the same temporary directory as pdfsizeopt.
    # This fixes the startup problem on Docker.
    #
    # Without this we get the error:
    # GPL Ghostscript 9.05: **** Could not open temporary file /foo/gs_sYvSR7
    tmp_dir = os.path.dirname(TMP_PREFIX) or '.'
    prefix = 'TMPDIR=%s TEMP=%s ' % ((ShellQuote(tmp_dir),) * 2)
  data = None
  gs_cmd = os.getenv('PDFSIZEOPT_GS', None)
  if gs_cmd is None:
    if sys.platform.startswith('win'):  # Windows: win32 or win64
      gs_cmd = find_on_path(os.path.join('pdfsizeopt_gswin', 'gswin32c.exe'))
      if gs_cmd is not None:
        # wine-1.2 works with or without quoting here, but Windows XP
        # requires quoting if the path to gs_cmd contains whitespace.
        gs_cmd = prefix + ShellQuote(gs_cmd)
        data = verify_gs(gs_cmd, is_verbose=is_verbose)
      if not data:
        gs_cmd = prefix + 'gswin32c'
        data = verify_gs(gs_cmd, is_verbose=is_verbose)
      if not data:
        # if os.getenv('PROCESSOR_ARCHITECTURE', 'x86') != 'x86':
        if not os.getenv('PROGRAMFILES(X86)', ''):  # 32-bit Windows.
          envs = ('PROGRAMFILES',)
        else:
          envs = ('PROGRAMW6432', 'PROGRAMFILES(X86)', 'PROGRAMFILES')
        gs_cmd = None
        for env_name in envs:
          env_value = os.getenv(env_name, '')
          if env_value:
            d = os.path.join(env_value, 'gs')
            if os.path.isdir(d):
              for entry in os.listdir(d):
                if re.match(r'gs[89][.]\d\d\Z', entry):
                  fn = os.path.join(d, entry, 'bin', 'gswin32c.exe')
                  if os.path.isfile(fn):
                    gs_cmd = prefix + ShellQuote(fn)
                    data = verify_gs(gs_cmd, is_verbose=is_verbose)
                    if data:
                      break
                    logger.log_info('this Ghostscript does not work: %s' % gs_cmd)
                    data = gs_cmd = None
              if gs_cmd is not None:
                break
      if not data or gs_cmd is None:
        raise RuntimeError('Could not find a working Ghostscript.')
    else:
      gs_cmd = find_on_path(os.path.join('pdfsizeopt_gs', 'gs'))
      if gs_cmd is not None:
        gs_cmd = prefix + ShellQuote(gs_cmd)
        data = verify_gs(gs_cmd, is_verbose=is_verbose)
      if not data and sys.platform.startswith('darwin'):
        # http://pages.uoregon.edu/koch/ and MacTeX have it.
        gs_cmd = find_on_path('gs-noX11')
        if gs_cmd is not None:
          gs_cmd = prefix + ShellQuote(gs_cmd)
          data = verify_gs(gs_cmd, is_verbose=is_verbose)
      if not data:
        gs_cmd, data = prefix + 'gs', None
  if data is None:
    data = verify_gs(gs_cmd, is_verbose=is_verbose)
  if not data:
    raise RuntimeError('Ghostscript does not seem to work: %s' % gs_cmd)
  if os.sep not in gs_cmd[len(prefix):]:
    gs_cmd2 = gs_cmd
    if gs_cmd2.startswith('"'):  # Approximately correct on Windows and Unix.
      i = gs_cmd2.find('"', 1)
      if i > 0:
        gs_cmd2 = gs_cmd[1 : i]
    gs_cmd_print = find_exe_on_path(gs_cmd2)
    if not gs_cmd_print:
      gs_cmd_print = gs_cmd
  else:
    gs_cmd_print = gs_cmd
  logger.log_info('using Ghostscript %s: %s' % (gs_cmd_print, data))
  _cache.append(gs_cmd)
  return gs_cmd


def redirect_output_unix(cmd, mode=False):
  """Returns cmd with output redirected.

  Args:
    cmd: A single-line shell command.
    mode: If None, stdout and stderr are discarded.
      Otherwise, if true, stderr is redirected to stdout.
        (This is also called pipe mode.)
      Otherwise, stdout is redirected to stderr.
  Returns:
    A modified shell command-line with stdout and stderr redirected.
    The stdout of the command will be redirected to its stderr.
  """
  if mode is None:
    suffix = '>/dev/null 2>&1'
  else:
    suffix = ('>&2', ' 2>&1')[bool(mode)]
  return 'exec%s;%s' % (suffix, cmd + '')


WINDOWS_COMMAND_QUOTED_OR_SEP_RE = re.compile(r'"[^"]+"|>[^&\n]*(?:&&?|\r\n|\n|\Z)|&&?|\r\n|\n')
"""Matches a double-quoted string literal or a command separator
(& or && or newline) or an stdout-redirect until the separator
on a Windows cmd.exe command-line.

We assume that the command doesn't contain 2>...

TODO(pts): Handle \" and \\ better in quoted strings.
"""


def redirect_output_windows(cmd, mode=False):
  """See the docstring of RedirectOutputUnix."""
  # These command suffixes indeed work on Windows.
  # https://serverfault.com/a/132964/27885
  if mode is None:
    suffix, suffixb = '>nul 2>&1', ' 2>nul '
  else:
    mode = bool(mode)
    suffix = ('>&2', ' 2>&1')[mode]
    # If mode is true and '>...' is in cmd, then prepend
    # ' 2>&1' in front of '>...'.
    ics = ('">', '"')[mode]
  cmd = cmd.strip()
  if (r'\\' in cmd or r'\"' in cmd or ' 2>' in cmd or  # Too complicated.
      ('&' not in cmd and '\n' not in cmd and
       (mode or '>' not in cmd))):  # Simple, appending will do.
    return cmd + suffix
  if mode is None:
    replf = (lambda match: suffix * (match.group()[0] not in '">') + suffixb * (match.group()[0] == '>') + match.group())
  else:
    replf = lambda match: suffix * (match.group()[0] not in ics) + match.group()
  return WINDOWS_COMMAND_QUOTED_OR_SEP_RE.sub(replf, cmd + '\n').rstrip('\n')


RedirectOutput = (redirect_output_unix, redirect_output_windows)[sys.platform.startswith('win')]

UNIX_SHELL_NEED_QUOTE_RE = re.compile(r'[^-_.+,:/a-zA-Z0-9]')


def shell_quote_unix(string):
  """Quotes (escapes) a command-line argument for Unix (Bourne shell).

  Args:
    string: Command-line argument to be quoted.
  Returns:
    Quoted command-line argument. Can be concatenated with any string.
  """
  string = str(string)
  if string and not UNIX_SHELL_NEED_QUOTE_RE.search(string):
    return string
  return "'%s'" % string.replace("'", "'\\''")


WINDOWS_SHELL_NEED_QUOTE_RE = re.compile(r'[ \t%"<>&|]')

WINDOWS_SHELL_QUOTE_RE = re.compile(r'(\\+)("|\Z)|(")')


def shell_quote_windows(string):
  """Quotes (escapes) a command-line argument for Windows.

  Does the quoting according to inverse of the rules defined in

  * https://stackoverflow.com/a/4094897/97248
  * https://msdn.microsoft.com/en-us/library/a1y7w461.aspx

  Args:
    string: Command-line argument to be quoted.
  Returns:
    Quoted command-line argument. If the result ends with backslash, please
    don't continue it with a string starting with double-quote.
  """
  # The following characters need escaping:
  # space, tab, %, ", <, >, &, |.
  # If the input contains none of these, the output is same as the
  # input. Otherwise, the output looks like "...", and within the "s:
  #
  # * \s not followed by a " are kept intact
  # * \s followed by a " are doubled and the " is escaped as \"
  # * " (not preceded by a \) is escaped as \"
  # * anything else is kept intact
  string = str(string)
  if string and not WINDOWS_SHELL_NEED_QUOTE_RE.search(string):
    return string
  return '"%s"' % WINDOWS_SHELL_QUOTE_RE.sub(
      lambda match: r'\\' * len(match.group(1) or '') + r'\"' * len(match.group(2) or match.group(3) or ''), string)


ShellQuote = (shell_quote_unix, shell_quote_windows)[sys.platform.startswith('win')]


def shell_quote_file_name(string, is_gs=False):
  # TODO(pts): Make it work on non-Unix systems.
  if string.startswith('-') and len(string) > 1:
    string = '.%s%s' % (os.sep, string)
  if sys.platform.startswith('win'):
    # This hack here is making sure that Ghostscript running on UNC path as
    # os.getcwd() will get absolute filenames. That's because we are doing the
    # 'c:&cd \\&' hack to run Ghotscript with 'c:\\' as os.getcwd(), and thus
    # it wouldn't find files with a relative filename.
    #
    # os.path.isabs and os.path.join don't work correctly, we implement our
    # own.
    if (is_gs and
        get_gs_command()[1 : 8] == ':&cd \\&' and
        not string.startswith('\\\\') and not string[1 : 3] == ':\\'):
      cwd = os.getcwd()
      if cwd.startswith('UNC\\'):  # wine-1.6.3.
        cwd = '\\' + cwd[3:]
      assert cwd.startswith('\\\\') or cwd[1 : 3] == ':\\', cwd
      if string.startswith('\\'):
        if cwd.startswith('\\\\'):
          raise NotImplementedError(
              'Unable to join pathnames: %s + %s' % (cwd, string))
        string = cwd[:2] + string
      else:
        string = os.path.join(cwd, string)
  return ShellQuote(string)


def format_percent_two_digits(num, den):
  if den == 0:
    return '?%'
  v = (num * 10000 + (den / 2)) // den
  return '%d.%02d%%' % divmod(v, 100)


def ensure_removed(file_name):
  try:
    os.remove(file_name)
  except OSError:
    assert not os.path.exists(file_name)


def rename(fromfn, tofn):
  """Like os.rename, but works on Windows if the destination exists."""
  try:
    os.rename(fromfn, tofn)
    return
  except OSError:
    # On Windows: WindowsError:
    # [Error 183] Cannot create a file when that file already exists.
    # sys.platform.startswith('win') and e[0] == 183):
    if os.path.exists(fromfn) and os.path.exists(tofn):
      try:
        try:
          os.remove(tofn)
        except OSError:
          pass
        os.rename(fromfn, tofn)
        return
      except OSError as e:
        pass
        logger.log_fatal('unable to rename from %r to %r: %s' % (fromfn, tofn, e), 4)


def find_on_path(file_name):
  """Find file_name on $PATH, and return the full pathname or None."""
  path = os.getenv('PATH', None)
  is_win = sys.platform.startswith('win')
  if path is None and not is_win:
    path = '/bin:/usr/bin'
  # TODO(pts): On Windows, do we want to append .exe to file_name?
  for item in path.split(os.pathsep):
    if (is_win and item.startswith('"') and item.endswith('"') and
        len(item) >= 2):
      # TODO(pts): Allow ';' within item.
      item = item[1 : -1].replace('""', '')
    if not item:
      item = '.'
    path_name = os.path.join(item, file_name)
    if os.path.exists(path_name):
      return path_name
  return None


NONWORD_RE = re.compile(r'\W+')


def get_cmd_name(cmd_pattern):
  cmd_name = cmd_pattern.split()  # TODO(pts): Windows unquote "...".
  if not cmd_name:
    return None
  if cmd_pattern.startswith('sam2p -j:quiet -pdf:2 -c zip:1:9 '):
    return 'sam2p_np'
  if cmd_pattern.startswith('sam2p -j:quiet -c zip:15:9 '):
    return 'sam2p_pr'
  cmd_name = os.path.basename(cmd_name[0].lower())
  cmd_name = NONWORD_RE.sub('_', cmd_name)
  return cmd_name


# Allowed in /Encoding of /TypeFont, pdf_reference_1-7.pdf page 414.
# gs -dNODISPLAY -q -P- -c '/MacRomanEncoding .findencoding === quit'
PDF_FONT_ENCODINGS = {
   'WinAnsiEncoding': '/.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /space /exclam /quotedbl /numbersign /dollar /percent /ampersand /quotesingle /parenleft /parenright /asterisk /plus /comma /hyphen /period /slash /zero /one /two /three /four /five /six /seven /eight /nine /colon /semicolon /less /equal /greater /question /at /A /B /C /D /E /F /G /H /I /J /K /L /M /N /O /P /Q /R /S /T /U /V /W /X /Y /Z /bracketleft /backslash /bracketright /asciicircum /underscore /grave /a /b /c /d /e /f /g /h /i /j /k /l /m /n /o /p /q /r /s /t /u /v /w /x /y /z /braceleft /bar /braceright /asciitilde /bullet /Euro /bullet /quotesinglbase /florin /quotedblbase /ellipsis /dagger /daggerdbl /circumflex /perthousand /Scaron /guilsinglleft /OE /bullet /Zcaron /bullet /bullet /quoteleft /quoteright /quotedblleft /quotedblright /bullet /endash /emdash /tilde /trademark /scaron /guilsinglright /oe /bullet /zcaron /Ydieresis /space /exclamdown /cent /sterling /currency /yen /brokenbar /section /dieresis /copyright /ordfeminine /guillemotleft /logicalnot /hyphen /registered /macron /degree /plusminus /twosuperior /threesuperior /acute /mu /paragraph /periodcentered /cedilla /onesuperior /ordmasculine /guillemotright /onequarter /onehalf /threequarters /questiondown /Agrave /Aacute /Acircumflex /Atilde /Adieresis /Aring /AE /Ccedilla /Egrave /Eacute /Ecircumflex /Edieresis /Igrave /Iacute /Icircumflex /Idieresis /Eth /Ntilde /Ograve /Oacute /Ocircumflex /Otilde /Odieresis /multiply /Oslash /Ugrave /Uacute /Ucircumflex /Udieresis /Yacute /Thorn /germandbls /agrave /aacute /acircumflex /atilde /adieresis /aring /ae /ccedilla /egrave /eacute /ecircumflex /edieresis /igrave /iacute /icircumflex /idieresis /eth /ntilde /ograve /oacute /ocircumflex /otilde /odieresis /divide /oslash /ugrave /uacute /ucircumflex /udieresis /yacute /thorn /ydieresis'.split(' '),
   'MacRomanEncoding': '/.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /space /exclam /quotedbl /numbersign /dollar /percent /ampersand /quotesingle /parenleft /parenright /asterisk /plus /comma /hyphen /period /slash /zero /one /two /three /four /five /six /seven /eight /nine /colon /semicolon /less /equal /greater /question /at /A /B /C /D /E /F /G /H /I /J /K /L /M /N /O /P /Q /R /S /T /U /V /W /X /Y /Z /bracketleft /backslash /bracketright /asciicircum /underscore /grave /a /b /c /d /e /f /g /h /i /j /k /l /m /n /o /p /q /r /s /t /u /v /w /x /y /z /braceleft /bar /braceright /asciitilde /.notdef /Adieresis /Aring /Ccedilla /Eacute /Ntilde /Odieresis /Udieresis /aacute /agrave /acircumflex /adieresis /atilde /aring /ccedilla /eacute /egrave /ecircumflex /edieresis /iacute /igrave /icircumflex /idieresis /ntilde /oacute /ograve /ocircumflex /odieresis /otilde /uacute /ugrave /ucircumflex /udieresis /dagger /degree /cent /sterling /section /bullet /paragraph /germandbls /registered /copyright /trademark /acute /dieresis /.notdef /AE /Oslash /.notdef /plusminus /.notdef /.notdef /yen /mu /.notdef /.notdef /.notdef /.notdef /.notdef /ordfeminine /ordmasculine /.notdef /ae /oslash /questiondown /exclamdown /logicalnot /.notdef /florin /.notdef /.notdef /guillemotleft /guillemotright /ellipsis /space /Agrave /Atilde /Otilde /OE /oe /endash /emdash /quotedblleft /quotedblright /quoteleft /quoteright /divide /.notdef /ydieresis /Ydieresis /fraction /currency /guilsinglleft /guilsinglright /fi /fl /daggerdbl /periodcentered /quotesinglbase /quotedblbase /perthousand /Acircumflex /Ecircumflex /Aacute /Edieresis /Egrave /Iacute /Icircumflex /Idieresis /Igrave /Oacute /Ocircumflex /.notdef /Ograve /Uacute /Ucircumflex /Ugrave /dotlessi /circumflex /tilde /macron /breve /dotaccent /ring /cedilla /hungarumlaut /ogonek /caron'.split(' '),
   'MacExpertEncoding': '/.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /space /exclamsmall /Hungarumlautsmall /centoldstyle /dollaroldstyle /dollarsuperior /ampersandsmall /Acutesmall /parenleftsuperior /parenrightsuperior /twodotenleader /onedotenleader /comma /hyphen /period /fraction /zerooldstyle /oneoldstyle /twooldstyle /threeoldstyle /fouroldstyle /fiveoldstyle /sixoldstyle /sevenoldstyle /eightoldstyle /nineoldstyle /colon /semicolon /.notdef /threequartersemdash /.notdef /questionsmall /.notdef /.notdef /.notdef /.notdef /Ethsmall /.notdef /.notdef /onequarter /onehalf /threequarters /oneeighth /threeeighths /fiveeighths /seveneighths /onethird /twothirds /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /ff /fi /fl /ffi /ffl /parenleftinferior /.notdef /parenrightinferior /Circumflexsmall /hypheninferior /Gravesmall /Asmall /Bsmall /Csmall /Dsmall /Esmall /Fsmall /Gsmall /Hsmall /Ismall /Jsmall /Ksmall /Lsmall /Msmall /Nsmall /Osmall /Psmall /Qsmall /Rsmall /Ssmall /Tsmall /Usmall /Vsmall /Wsmall /Xsmall /Ysmall /Zsmall /colonmonetary /onefitted /rupiah /Tildesmall /.notdef /.notdef /asuperior /centsuperior /.notdef /.notdef /.notdef /.notdef /Aacutesmall /Agravesmall /Acircumflexsmall /Adieresissmall /Atildesmall /Aringsmall /Ccedillasmall /Eacutesmall /Egravesmall /Ecircumflexsmall /Edieresissmall /Iacutesmall /Igravesmall /Icircumflexsmall /Idieresissmall /Ntildesmall /Oacutesmall /Ogravesmall /Ocircumflexsmall /Odieresissmall /Otildesmall /Uacutesmall /Ugravesmall /Ucircumflexsmall /Udieresissmall /.notdef /eightsuperior /fourinferior /threeinferior /sixinferior /eightinferior /seveninferior /Scaronsmall /.notdef /centinferior /twoinferior /.notdef /Dieresissmall /.notdef /Caronsmall /osuperior /fiveinferior /.notdef /commainferior /periodinferior /Yacutesmall /.notdef /dollarinferior /.notdef /.notdef /Thornsmall /.notdef /nineinferior /zeroinferior /Zcaronsmall /AEsmall /Oslashsmall /questiondownsmall /oneinferior /Lslashsmall /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /Cedillasmall /.notdef /.notdef /.notdef /.notdef /.notdef /OEsmall /figuredash /hyphensuperior /.notdef /.notdef /.notdef /.notdef /exclamdownsmall /.notdef /Ydieresissmall /.notdef /onesuperior /twosuperior /threesuperior /foursuperior /fivesuperior /sixsuperior /sevensuperior /ninesuperior /zerosuperior /.notdef /esuperior /rsuperior /tsuperior /.notdef /.notdef /isuperior /ssuperior /dsuperior /.notdef /.notdef /.notdef /.notdef /.notdef /lsuperior /Ogoneksmall /Brevesmall /Macronsmall /bsuperior /nsuperior /msuperior /commasuperior /periodsuperior /Dotaccentsmall /Ringsmall /.notdef /.notdef /.notdef /.notdef'.split(' '),
}
NONE_ENCODING = [None]  * 256

BOOL_VALUES = {
    'on': True,
    'off': False,
    'yes': True,
    'no': False,
    '1': True,
    '0': False,
    'true': True,
    'false': False,
}


def parse_bool_flag(key, flag_value):
  flag_value_lower = flag_value.lower()
  if flag_value_lower not in BOOL_VALUES:
    raise getopt.GetoptError('flag %s=%s needs a bool value' % (key, flag_value))
  return BOOL_VALUES[flag_value_lower]


def parse_uint_flag(key, flag_value):
  try:
    value = int(flag_value)
    if value < 0:
      raise ValueError
  except ValueError:
    raise getopt.GetoptError('flag %s=%s needs a nonnegative integer value' % (key, flag_value))
  return value


def get_dir(file_name):
  readlink = getattr(os, 'readlink', None)  # Not available on Windows.
  if readlink:
    while 1:
      try:
        target_name = readlink(file_name)
      except OSError:  # Happens on Linux if file_name is not a symlink.
        break
      if target_name == file_name:  # This doesn't happen on Linux.
        break
      file_name = target_name
  return os.path.dirname(file_name)


def get_version_spec(zip_file):
  if zip_file and os.path.isfile(zip_file):
    main_file = zip_file
    zip_msg = ' ZIP'
  else:
    main_file = __file__
    zip_msg = ''
  if main_file.endswith('.pyc'):
    main_file = main_file[:-4] + '.py'
  try:
    size = os.stat(main_file).st_size
  except OSError:
    # We'll get this if main_file is within a .zip file (on $PYTHONPATH).
    # Since the built-in linecache.py doesn't attempt to read such files,
    # we don't do that either, and keep size = None for simplicity.
    size = None
  rev = None  # TODO(pts): Do we want to display a git commit id?
  return 'pdfsizeopt%s r%s size=%s' % (zip_msg, rev or 'UNKNOWN', size)


def get_used_script_dir(script_dir, zip_file):
  # script_file = sys.modules['__main__'].__file__
  if script_dir:
    return script_dir
  elif zip_file and os.path.isfile(zip_file):
    return os.path.dirname(os.path.abspath(zip_file))
  else:
    return os.path.dirname(os.path.abspath(__file__))


def get_libexec_dir(used_script_dir):
  if sys.platform.startswith('win'):
    xdir = os.path.join(used_script_dir, 'pdfsizeopt_win32exec')
    if os.path.isdir(xdir):
      return xdir
  xdir = os.path.join(used_script_dir, 'pdfsizeopt_libexec')
  if os.path.isdir(xdir):
    return xdir
  return None


def prepend_to_path(extrapath_dir):
  logger.log_info('prepending to PATH: %s' % extrapath_dir)
  # When adding to the PATH, we mustn't call ShellQuote on extrapath_dir on
  # Unix systems. On Windows XP ... Windows 10, it works with or without
  # ShellQuote (i.e. "s round the directory name), but on wine-1.6.2, directory
  # names in PATH don't work with "s. So we are not calling ShellQuote here.
  os.environ['PATH'] = '%s%s%s' % (extrapath_dir, os.pathsep, os.getenv('PATH', ''))


def setup_tmp_prefix(output_file_name, tmp_dir):
  global TMP_PREFIX  # !! TODO(pts): Pass it around? Or GetGsCommand()?
  if not tmp_dir:
    if sys.platform.startswith('win'):
      tmp_dir = os.getenv('TEMP', '')
    else:
      tmp_dir = os.getenv('TMPDIR', '')
    if not (tmp_dir and os.path.isdir(tmp_dir)):
      if output_file_name:
        tmp_dir = os.path.dirname(output_file_name)
      else:
        tmp_dir = '..'
  tmp_basename = 'psotmp.%d.' % os.getpid()
  if tmp_dir == '.':
    TMP_PREFIX = tmp_basename
  else:
    TMP_PREFIX = os.path.join(tmp_dir, tmp_basename)
  if TMP_PREFIX.startswith('/') and sys.platform.startswith('win'):
    # pngout doesn't work otherwise, because it treats '/' as flag.
    TMP_PREFIX = TMP_PREFIX.replace('/', os.sep)


def display_help(mode, argv0):
  logger.log_info('usage for statistics computation: %s --stats <input.pdf>' % argv0)
  logger.log_info('usage for size optimization: %s [<flag>...] <input.pdf> [<output.pdf>]' % argv0)
  if mode == 'helpshort':
    logger.log_info('specify --help to get help on each flag')
  else:
    logger.log_info('flags:\n\n%s' % FLAGS_HELP.strip())


class Flags(object):
  """Class for parsing the command-line of pdfsizeopt."""

  BOOL_FLAG_WITH_DEFAULT_RE = re.compile(r'(--\w[-\w]*)=YES_NO;(?: default: (yes|no)|(.|\n)*)\Z')

  FLAG_PREFIX_RE = re.compile(r'--(\w[-\w]*=?)')

  def __init__(self):
    _BOOL_FLAG_WITH_DEFAULT_RE = self.BOOL_FLAG_WITH_DEFAULT_RE
    _FLAG_PREFIX_RE = self.FLAG_PREFIX_RE
    self.getopt_flag_names = getopt_flag_names = []
    self.bool_flag_names = bool_flag_names = set()
    for line in FLAGS_HELP.split('\n'):
      match = _BOOL_FLAG_WITH_DEFAULT_RE.match(line)
      if match:
        assert match.group(2), 'Invalid bool flag syntax: ' + line
        flag_name = match.group(1)[2:].replace('-', '_')
        setattr(self, flag_name, parse_bool_flag(match.group(1), match.group(2)))
        bool_flag_names.add(flag_name)
      match = _FLAG_PREFIX_RE.match(line)
      if match:
        getopt_flag_names.append(match.group(1))  # Multiple times OK.

    # TODO(pts): Add =auto for use_pngout, use_jbig2, use_multivalent.
    self.use_pngout = self.use_jbig2 = self.use_sam2p_pr = None
    self.mode = 'optimize'
    self.img_cmds = []
    self.args = []
    self.verbosity = 190
    self.tmp_dir = None

  def parse(self, argv):
    def long_has_args(opt, longopts):
      if opt in longopts:
        return False, opt
      elif opt + '=' in longopts:
        return True, opt
      else:
        raise getopt.GetoptError('option --%s not recognized' % opt, opt)

    # Disable prefix matching, e.g. disable `--use-pngo=no'.
    # TODO(pts): Undo this and make it thread-safe.
    getopt.long_has_args = long_has_args

    f = self
    if len(argv) < 2:
      f.mode = 'helpshort'
    # getopt.getopt wouldn't allow option and non-option arguments to be
    # intermixed.
    opts, f.args[:] = getopt.gnu_getopt(argv[1:], '+', self.getopt_flag_names)

    for key, value in opts:
      assert key.startswith('--')
      flag_name = key[2:].replace('-', '_')
      if flag_name in ('stats', 'help', 'helpshort', 'version', 'optimize'):
        f.mode = flag_name
      elif flag_name == 'use_image_optimizer':
        value = value.strip()
        if not value:
          raise getopt.GetoptError('Empty image optimizer command.')
        if len(value.split()) < 2:
          f.img_cmds.extend(filter(None, value.split(',')))
        else:
          # Special value 'none' and 'none' are also OK.
          f.img_cmds.append(value)
      elif flag_name == 'do_double_check_missing_glyphs':  # Legacy flag name.
        f.do_double_check_type1c_output = parse_bool_flag(key, value)
      elif flag_name == 'v':
        f.verbosity = parse_uint_flag(key, value)
      elif flag_name == 'quiet':
        f.verbosity = 20
      elif flag_name == 'tmp_dir':
        setattr(f, flag_name, value)
      elif flag_name in f.bool_flag_names:
        setattr(f, flag_name, parse_bool_flag(key, value))
      else:
        assert False, 'unknown flag %s' % key  # Can't happen, getopt output.


def optimize(argv, script_dir=None, zip_file=None):
  global VERBOSITY
  welcome_msg = 'This is %s.' % get_version_spec(zip_file)
  try:
    if not argv:
      argv = ['pdfsizeopt']
    f = Flags()
    # TODO(pts): Use `import win32api; print(win32api.GetCommandLine())' on
    # Windows to detect double quotes around file names, and thus accept a PDF
    # with double quotes in the file name.
    f.parse(argv)
    VERBOSITY = f.verbosity

    if f.mode == 'optimize':
      if not f.args:
        if not f.do_debug_gs and not f.do_debug_image_optimizers:
          raise getopt.GetoptError('missing input filename in command-line')
        output_file_name = file_name = None
      elif len(f.args) == 1:
        file_name = f.args[0]
        if file_name[-4:].lower() == '.pdf':
          output_file_name = file_name[:-4]
        else:
          output_file_name = file_name
        output_file_name += '.pso.pdf'
      elif len(f.args) == 2:
        file_name = f.args[0]
        output_file_name = f.args[1]
      else:
        raise getopt.GetoptError('too many command-line args')

      if f.do_generate_object_stream and not f.do_generate_xref_stream:
        raise getopt.GetoptError('--do-generate-object-stream=yes requires --do-generate-xref-stream=yes')

  except getopt.GetoptError as exc:
    logger.log_fatal('%s\nfatal: error in command line: %s' % (welcome_msg, exc), 1)

  if f.mode in ('help', 'helpshort'):
    f.verbosity = VERBOSITY = 190  # Make `--quiet --help' also display.
    logger.log_info(welcome_msg)
    display_help(f.mode, argv[0])
    return
  logger.log_info(welcome_msg)
  assert f.mode == 'optimize'  # Implemented below.

  used_script_dir = get_used_script_dir(script_dir, zip_file)
  libexec_dir = get_libexec_dir(used_script_dir)
  if libexec_dir is not None:
    prepend_to_path(libexec_dir)  # Find external tools in libexec_dir first...
  else:
    prepend_to_path(used_script_dir)  # ... otherwise, find them in script dir.
  del used_script_dir  # Make sure it's not used.

  # Call it before the first call to GetGsCommand(...).
  setup_tmp_prefix(output_file_name, f.tmp_dir)

  if output_file_name is None:  # Just --do-debug-gs=yes.
    return

  # It's OK that file_name == output_file_name: we don't read and write them
  # at the same time.
  pdf = PdfData(do_ignore_generation_numbers=f.do_ignore_generation_numbers).load(file_name)
  pdf.remove_unused_objs()
  pdf.fix_all_bad_numbers()
  if f.do_optimize_streams:
    # We call this before pdf.OptimizeObjs, so pdf.OptimizeObjs can found
    # more duplicate objs (in case the same stream data was compressed
    # differently).
    pdf.optimize_streams(do_decompress_only=False)
  if f.do_optimize_objs or f.do_remove_generational_objs:
    # TODO(pts): Do only a simpler optimization with renumbering if
    # f.do_optimize_objs is false and f.do_remove_generational_objs is true.
    pdf.optimize_objs(do_unify_pages=f.do_unify_pages)
  elif f.do_optimize_obj_heads:
    pdf.trailer.head = PdfObj.compress_value(pdf.trailer.head)
    for obj in pdf.objs.values():
      obj.head = PdfObj.compress_value(obj.head)
  # TODO(pts): Better handle which of f.do_compress_uncompressed_streams
  #            and f.do_decompress_most_streams takes precedence. Maybe
  #            that which is specified on the command-line (?).
  if (f.do_compress_uncompressed_streams and not f.do_decompress_most_streams):
    pdf.compress_uncompressed_streams()
  pdf.save(
      output_file_name + '.tmp',
      display_file_name=output_file_name,
      do_update_file_meta=True,
      do_generate_xref_stream=f.do_generate_xref_stream,
      do_generate_object_stream=f.do_generate_object_stream,
      is_flate_ok=(f.do_compress_uncompressed_streams and not f.do_decompress_most_streams))
  rename(output_file_name + '.tmp', output_file_name)


def main():
  __file__ = globals()['__file__']
  print(__file__)
  script_dir = os.path.dirname(__file__)
  try:
    __file__ = os.path.join(script_dir, os.readlink(__file__))
    script_dir = os.path.dirname(__file__)
  except (OSError, AttributeError, NotImplementedError):
    pass
  if os.path.isfile(os.path.join(script_dir, 'lib', 'pdfsizeopt', 'main.py')):
    sys.path[0] = os.path.join(script_dir, 'lib')

  sys.exit(optimize(sys.argv, script_dir=script_dir))
